// <auto-generated />
using ApiMantenimiento.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMantenimiento.Migrations
{
    [DbContext(typeof(MantenimientoDbContext))]
    [Migration("20260523185601_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.AreaOperacion", b =>
                {
                    b.Property<string>("cod_area_ope")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cod_area_ope");

                    b.Property<string>("nomb_area")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nomb_area");

                    b.HasKey("cod_area_ope");

                    b.ToTable("AreaOperacion", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Equipo", b =>
                {
                    b.Property<int>("id_equipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_equipo"));

                    b.Property<string>("AreaOperacioncod_area_ope")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("cod_are_ope")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("cod_eqp")
                        .IsRequired()
                        .HasColumnType("char(18)");

                    b.Property<string>("estado_operativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("horometro_actual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("horometro_inicial")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("id_flota")
                        .HasColumnType("int");

                    b.Property<string>("num_serie")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("placa_eqp")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id_equipo");

                    b.HasIndex("AreaOperacioncod_area_ope");

                    b.HasIndex("id_flota");

                    b.ToTable("Equipo", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Flota", b =>
                {
                    b.Property<int>("id_flota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_flota"));

                    b.Property<string>("cod_flota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_modelo")
                        .HasColumnType("int");

                    b.Property<string>("nombre_flota")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tipo_control")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_flota");

                    b.ToTable("Flota", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.MarcaEquipo", b =>
                {
                    b.Property<int>("id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_marca"));

                    b.Property<string>("nombre_marca")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nombre_marca");

                    b.HasKey("id_marca");

                    b.ToTable("MarcaEquipo", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.ModeloEquipo", b =>
                {
                    b.Property<int>("id_modelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_modelo"));

                    b.Property<int>("id_marca")
                        .HasColumnType("int");

                    b.Property<int>("id_tipo_eqp")
                        .HasColumnType("int");

                    b.Property<string>("nomb_modelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_modelo");

                    b.HasKey("id_modelo");

                    b.HasIndex("id_marca");

                    b.HasIndex("id_tipo_eqp");

                    b.ToTable("ModeloEquipo", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.TipoEquipo", b =>
                {
                    b.Property<int>("id_tipo_eqp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipo_eqp"));

                    b.Property<string>("cod_equipo")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("nombre_tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_tipo_eqp");

                    b.ToTable("TipoEquipos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Equipo", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.AreaOperacion", "AreaOperacion")
                        .WithMany("Equipos")
                        .HasForeignKey("AreaOperacioncod_area_ope")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.Flota", "Flota")
                        .WithMany("Equipos")
                        .HasForeignKey("id_flota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaOperacion");

                    b.Navigation("Flota");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.ModeloEquipo", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.MarcaEquipo", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("id_marca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.TipoEquipo", "TipoEquipo")
                        .WithMany("ModeloEquipos")
                        .HasForeignKey("id_tipo_eqp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.AreaOperacion", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Flota", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.MarcaEquipo", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.TipoEquipo", b =>
                {
                    b.Navigation("ModeloEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
