// <auto-generated />
using System;
using ApiMantenimiento.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMantenimiento.Migrations
{
    [DbContext(typeof(MantenimientoDbContext))]
    [Migration("20260605161532_CorreccionEstrategia")]
    partial class CorreccionEstrategia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MAlmacen.CategoriaMaterial", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("cod_cat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nombre_categoria")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id_categoria");

                    b.HasIndex("cod_cat")
                        .IsUnique();

                    b.ToTable("Alm_CategoriaMaterial", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MAlmacen.Material", b =>
                {
                    b.Property<int>("id_material")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_material"));

                    b.Property<string>("cod_materia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<int>("id_unidad")
                        .HasColumnType("int");

                    b.Property<decimal>("stock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_material");

                    b.HasIndex("cod_materia")
                        .IsUnique();

                    b.HasIndex("id_categoria");

                    b.HasIndex("id_unidad");

                    b.ToTable("Alm_Material", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MAlmacen.UnidadMedida", b =>
                {
                    b.Property<int>("id_unidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_unidad"));

                    b.Property<string>("abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("nombre_unidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_unidad");

                    b.ToTable("Alm_UnidadMedida", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.Empleado", b =>
                {
                    b.Property<string>("dni_empleado")
                        .HasColumnType("char(8)");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("apellido2")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("codigo_empleado")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("id_rol")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("telf")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("dni_empleado");

                    b.HasIndex("id_rol");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.ExpedienteDocumentoEmpleado", b =>
                {
                    b.Property<int>("id_exp_doc_emp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_exp_doc_emp"));

                    b.Property<string>("cod_tipo_doc_emp")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("codigo_exp_emp")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("documento_url")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("fecha_vencimiento")
                        .HasColumnType("datetime");

                    b.HasKey("id_exp_doc_emp");

                    b.HasIndex("cod_tipo_doc_emp");

                    b.HasIndex("codigo_exp_emp");

                    b.ToTable("ExpedienteDocumentoEmpleado", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.ExpedienteEmpleado", b =>
                {
                    b.Property<string>("codigo_exp_emp")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("dni_empleado")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.HasKey("codigo_exp_emp");

                    b.HasIndex("dni_empleado")
                        .IsUnique();

                    b.ToTable("ExpedienteEmpleado", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.Rol", b =>
                {
                    b.Property<int>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_rol"));

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("prefijo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id_rol");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.TipoDocumentoEmpleado", b =>
                {
                    b.Property<string>("cod_tipo_doc_emp")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("nombre_tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("cod_tipo_doc_emp");

                    b.ToTable("TipoDocumentoEmpleado", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.AreaOperacion", b =>
                {
                    b.Property<string>("cod_area_ope")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cod_area_ope");

                    b.Property<string>("nomb_area")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nomb_area");

                    b.HasKey("cod_area_ope");

                    b.ToTable("AreaOperacion", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Equipo", b =>
                {
                    b.Property<int>("id_equipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_equipo"));

                    b.Property<string>("cod_are_ope")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("cod_eqp")
                        .IsRequired()
                        .HasColumnType("char(18)");

                    b.Property<string>("estado_operativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("horometro_actual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("horometro_inicial")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("id_flota")
                        .HasColumnType("int");

                    b.Property<string>("num_serie")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("placa_eqp")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id_equipo");

                    b.HasIndex("cod_are_ope");

                    b.HasIndex("id_flota");

                    b.ToTable("Equipo", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Expediente", b =>
                {
                    b.Property<string>("codigo_exp")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("id_equipo")
                        .HasColumnType("int");

                    b.HasKey("codigo_exp");

                    b.HasIndex("id_equipo")
                        .IsUnique();

                    b.ToTable("Expediente", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.ExpedienteDocumento", b =>
                {
                    b.Property<int>("id_expediente_documento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_expediente_documento"));

                    b.Property<string>("cod_tipo_documento")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("codigo_exp")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("documento_url")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("fecha_vencimiento")
                        .HasColumnType("datetime");

                    b.HasKey("id_expediente_documento");

                    b.HasIndex("cod_tipo_documento");

                    b.HasIndex("codigo_exp");

                    b.ToTable("ExpedienteDocumento", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Flota", b =>
                {
                    b.Property<int>("id_flota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_flota"));

                    b.Property<string>("cod_flota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_modelo")
                        .HasColumnType("int");

                    b.Property<string>("nombre_flota")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tipo_control")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_flota");

                    b.HasIndex("id_modelo");

                    b.ToTable("Flota", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.HistorialHorometros", b =>
                {
                    b.Property<string>("codigo_hist")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("dni_conductor")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("horas_operadas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("id_equipo")
                        .HasColumnType("int");

                    b.Property<decimal>("lectura_actual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("lectura_anterior")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("codigo_hist");

                    b.HasIndex("dni_conductor");

                    b.HasIndex("id_equipo");

                    b.ToTable("HistorialHorometros", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.MarcaEquipo", b =>
                {
                    b.Property<int>("id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_marca"));

                    b.Property<string>("nombre_marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_marca");

                    b.HasKey("id_marca");

                    b.ToTable("MarcaEquipo", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.ModeloEquipo", b =>
                {
                    b.Property<int>("id_modelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_modelo"));

                    b.Property<int>("id_marca")
                        .HasColumnType("int");

                    b.Property<int>("id_tipo_eqp")
                        .HasColumnType("int");

                    b.Property<string>("nomb_modelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_modelo");

                    b.HasKey("id_modelo");

                    b.HasIndex("id_marca");

                    b.HasIndex("id_tipo_eqp");

                    b.ToTable("ModeloEquipo", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.TipoDocumento", b =>
                {
                    b.Property<string>("cod_tipo_documento")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("nombre_tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("cod_tipo_documento");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.TipoEquipo", b =>
                {
                    b.Property<int>("id_tipo_eqp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipo_eqp"));

                    b.Property<string>("cod_equipo")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("nombre_tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_tipo_eqp");

                    b.ToTable("TipoEquipos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.ActividadSistema", b =>
                {
                    b.Property<int>("id_actividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_actividad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_actividad"));

                    b.Property<string>("cod_act")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cod_act");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("duracion")
                        .HasColumnType("int")
                        .HasColumnName("duracion");

                    b.Property<bool>("estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<int>("id_sistema")
                        .HasColumnType("int")
                        .HasColumnName("id_sistema");

                    b.Property<string>("medida_duracion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("medida_duracion");

                    b.Property<string>("nombre_actividad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_actividad");

                    b.HasKey("id_actividad");

                    b.HasIndex("id_sistema");

                    b.ToTable("actividades_sistema", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.Estrategia", b =>
                {
                    b.Property<int>("id_estrategia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_estrategia"));

                    b.Property<string>("cod_estrategia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("id_equipo")
                        .HasColumnType("int");

                    b.Property<int?>("id_flota")
                        .HasColumnType("int");

                    b.Property<string>("titulo_estrategia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_estrategia");

                    b.HasIndex("id_equipo");

                    b.HasIndex("id_flota");

                    b.ToTable("Estrategia", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.EstrategiaDetalle", b =>
                {
                    b.Property<int>("id_detalle_estrg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_detalle_estrg"));

                    b.Property<int>("id_estrategia")
                        .HasColumnType("int");

                    b.Property<string>("nombre_medida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("porcentaje_tol")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tipo_pm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("tolerancia_inf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tolerancia_sup")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("umbral_mant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("uni_med")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id_detalle_estrg");

                    b.HasIndex("id_estrategia");

                    b.ToTable("EstrategiaDetalle", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimiento", b =>
                {
                    b.Property<int>("id_plan_mant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_plan_mant"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_estrategia")
                        .HasColumnType("int");

                    b.HasKey("id_plan_mant");

                    b.HasIndex("id_estrategia");

                    b.ToTable("Man_PlanMantenimiento", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimientoActividad", b =>
                {
                    b.Property<int>("id_plan_actividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_plan_actividad"));

                    b.Property<decimal?>("cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("id_actividad")
                        .HasColumnType("int");

                    b.Property<int>("id_detalle_estrg")
                        .HasColumnType("int");

                    b.Property<int?>("id_material")
                        .HasColumnType("int");

                    b.Property<int>("id_plan_mant")
                        .HasColumnType("int");

                    b.HasKey("id_plan_actividad");

                    b.HasIndex("id_actividad");

                    b.HasIndex("id_detalle_estrg");

                    b.HasIndex("id_material");

                    b.HasIndex("id_plan_mant");

                    b.ToTable("Man_PlanMantenimientoActividad", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimientoPersonal", b =>
                {
                    b.Property<int>("id_plan_personal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_plan_personal"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("id_plan_mant")
                        .HasColumnType("int");

                    b.Property<int>("id_rol")
                        .HasColumnType("int");

                    b.HasKey("id_plan_personal");

                    b.HasIndex("id_rol");

                    b.HasIndex("id_plan_mant", "id_rol")
                        .IsUnique();

                    b.ToTable("Man_PlanMantenimientoPersonal", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.SistemaEquipo", b =>
                {
                    b.Property<int>("id_sistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sistema");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_sistema"));

                    b.Property<string>("cod_sist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cod_sist");

                    b.Property<string>("nombre_sist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_sist");

                    b.HasKey("id_sistema");

                    b.ToTable("sistema_equipo", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MSecurity.Usuario", b =>
                {
                    b.Property<string>("dni_empleado")
                        .HasColumnType("char(8)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("dni_empleado");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MAlmacen.Material", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MAlmacen.CategoriaMaterial", "CategoriaMaterial")
                        .WithMany()
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MAlmacen.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("id_unidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaMaterial");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.Empleado", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MEmpleados.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.ExpedienteDocumentoEmpleado", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MEmpleados.TipoDocumentoEmpleado", "TipoDocumentoEmpleado")
                        .WithMany("DetallesDocumento")
                        .HasForeignKey("cod_tipo_doc_emp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MEmpleados.ExpedienteEmpleado", "ExpedienteEmpleado")
                        .WithMany("DetallesDocumento")
                        .HasForeignKey("codigo_exp_emp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpedienteEmpleado");

                    b.Navigation("TipoDocumentoEmpleado");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.ExpedienteEmpleado", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MEmpleados.Empleado", "Empleado")
                        .WithOne("ExpedienteEmpleado")
                        .HasForeignKey("ApiMantenimiento.Models.Entitys.MEmpleados.ExpedienteEmpleado", "dni_empleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Equipo", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.AreaOperacion", "AreaOperacion")
                        .WithMany("Equipos")
                        .HasForeignKey("cod_are_ope")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.Flota", "Flota")
                        .WithMany("Equipos")
                        .HasForeignKey("id_flota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaOperacion");

                    b.Navigation("Flota");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Expediente", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.Equipo", "Equipo")
                        .WithOne("Expediente")
                        .HasForeignKey("ApiMantenimiento.Models.Entitys.MFlota.Expediente", "id_equipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.ExpedienteDocumento", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.TipoDocumento", "TipoDocumento")
                        .WithMany("DetallesDocumento")
                        .HasForeignKey("cod_tipo_documento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.Expediente", "Expediente")
                        .WithMany("DetallesDocumento")
                        .HasForeignKey("codigo_exp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Flota", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.ModeloEquipo", "ModeloEquipo")
                        .WithMany("Flotas")
                        .HasForeignKey("id_modelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModeloEquipo");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.HistorialHorometros", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MEmpleados.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("dni_conductor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.Equipo", null)
                        .WithMany()
                        .HasForeignKey("id_equipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.ModeloEquipo", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.MarcaEquipo", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("id_marca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.TipoEquipo", "TipoEquipo")
                        .WithMany("ModeloEquipos")
                        .HasForeignKey("id_tipo_eqp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.ActividadSistema", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MMantenimiento.SistemaEquipo", "SistemaEquipo")
                        .WithMany("Actividades")
                        .HasForeignKey("id_sistema")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SistemaEquipo");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.Estrategia", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("id_equipo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiMantenimiento.Models.Entitys.MFlota.Flota", "Flota")
                        .WithMany()
                        .HasForeignKey("id_flota")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipo");

                    b.Navigation("Flota");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.EstrategiaDetalle", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MMantenimiento.Estrategia", "Estrategia")
                        .WithMany("Detalles")
                        .HasForeignKey("id_estrategia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estrategia");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimiento", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MMantenimiento.Estrategia", "Estrategia")
                        .WithMany()
                        .HasForeignKey("id_estrategia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estrategia");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimientoActividad", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MMantenimiento.ActividadSistema", "ActividadSistema")
                        .WithMany()
                        .HasForeignKey("id_actividad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MMantenimiento.EstrategiaDetalle", "EstrategiaDetalle")
                        .WithMany()
                        .HasForeignKey("id_detalle_estrg")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MAlmacen.Material", "Material")
                        .WithMany()
                        .HasForeignKey("id_material")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimiento", "PlanMantenimiento")
                        .WithMany("PlanMantenimientoActividades")
                        .HasForeignKey("id_plan_mant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActividadSistema");

                    b.Navigation("EstrategiaDetalle");

                    b.Navigation("Material");

                    b.Navigation("PlanMantenimiento");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimientoPersonal", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimiento", "PlanMantenimiento")
                        .WithMany("PlanMantenimientoPersonales")
                        .HasForeignKey("id_plan_mant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMantenimiento.Models.Entitys.MEmpleados.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanMantenimiento");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MSecurity.Usuario", b =>
                {
                    b.HasOne("ApiMantenimiento.Models.Entitys.MEmpleados.Empleado", "Empleado")
                        .WithOne()
                        .HasForeignKey("ApiMantenimiento.Models.Entitys.MSecurity.Usuario", "dni_empleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.Empleado", b =>
                {
                    b.Navigation("ExpedienteEmpleado")
                        .IsRequired();
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.ExpedienteEmpleado", b =>
                {
                    b.Navigation("DetallesDocumento");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MEmpleados.TipoDocumentoEmpleado", b =>
                {
                    b.Navigation("DetallesDocumento");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.AreaOperacion", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Equipo", b =>
                {
                    b.Navigation("Expediente")
                        .IsRequired();
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Expediente", b =>
                {
                    b.Navigation("DetallesDocumento");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.Flota", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.MarcaEquipo", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.ModeloEquipo", b =>
                {
                    b.Navigation("Flotas");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.TipoDocumento", b =>
                {
                    b.Navigation("DetallesDocumento");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MFlota.TipoEquipo", b =>
                {
                    b.Navigation("ModeloEquipos");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.Estrategia", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.PlanMantenimiento", b =>
                {
                    b.Navigation("PlanMantenimientoActividades");

                    b.Navigation("PlanMantenimientoPersonales");
                });

            modelBuilder.Entity("ApiMantenimiento.Models.Entitys.MMantenimiento.SistemaEquipo", b =>
                {
                    b.Navigation("Actividades");
                });
#pragma warning restore 612, 618
        }
    }
}
